### ISSUE TITLE
Console error missing asset

### ISSUE THREAD

**Issue by apogeegurus** [apogeegurus/junk-deal#10]
Steps to reproduce: 
1. Load any page 
2. Check web inspector console
3. Observe the following error: 

Error while trying to use the following icon from the Manifest: http://localhost:8080/android-icon-144x144.png (Download error or resource isn't a valid image)

<img width="1174" alt="Screen Shot 2019-12-12 at 9 36 47 AM" src="https://user-images.githubusercontent.com/58563978/70735365-f651a380-1cc2-11ea-8c26-244829384e5c.png">

**Comment by apogeegurus** [comment]
Looks like this issue is back again.
Screenshot attached.
<img width="1157" alt="Screen Shot 2019-12-18 at 7 59 46 AM" src="https://user-images.githubusercontent.com/58563978/71102037-96e50f00-216c-11ea-869b-534373335fa1.png">

**Comment by hovnaz96** [comment]
please check with incognito it's cache issue

**Comment by apogeegurus** [comment]
This has something to do with manifesti cache. This issue should be resolved once in production.
Closing for now.
