### ISSUE TITLE
Mobile : Chrome : The nav (global) is too wide(too much height) especially bad in landscape orientation

### ISSUE THREAD

**Issue by apogeegurus** [apogeegurus/junk-deal#38]
Mobile : Chrome : The nav (global) is too wide especially bad in landscape orientation. 
I think it should have a little less height so it doesn't cover 1/3 of the page.

<img width="674" alt="Screen Shot 2020-01-19 at 10 45 23 AM" src="https://user-images.githubusercontent.com/58563978/72686386-feaeb280-3aa8-11ea-874e-3acd0130de7c.png">

**Comment by Nemet-design** [comment]
I don’t think this is a problem. The moist of the people use the same grip and portrait orientation of the screen while using a phones.

**Comment by apogeegurus** [comment]
So moving this to Done! 
We also discussed this with Dima and agreed that this is okay.
